--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NayLeDev/https-github.com-Zinkil-YT-Pandaz-Core
build-by-default: true
branches:
- main
projects:
  https-github.com-Zinkil-YT-Pandaz-Core:
    path: ""
...
